[app_servers]
app-server-1 ansible_host=10.20.1.240
app-server-2 ansible_host=10.20.2.29

[db_servers]
db-server ansible_host=10.20.1.136

[monitoring_servers]
monitoring-server ansible_connection=local

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ubuntu/.ssh/ansible-control
